### ISSUE TITLE
Use an environment variable for google analytics ID

### ISSUE THREAD

**Issue by teneightfive** [nhsuk/gp-to-services#55]
The GA ID is currently hard coded into this file (https://github.com/nhsalpha/gp-to-services/blob/master/public/js/tracking/google-analytics.js)[https://github.com/nhsalpha/gp-to-services/blob/master/public/js/tracking/google-analytics.js].

Having it hard coded will mean that the analytics will get hit with development data and skew any conclusions that can be made. 

Moving to an environment variable means different environments can be more flexible and send to different accounts.

Also, as part of this it would be worth setting up a separate property to the beta.nhs.uk property so that the data can be queried separately more easily.

**Comment by neilbmclaughlin** [comment]
The GA code used has been changed to point at a connecting for services specific one (UA-67365892-6).

It is still hard coded but making this quick change ahead of the release of the beta tomorrow gives us time to get the usage of env variables right.

We'll not close the issue until the full fix is in place.

**Comment by teneightfive** [comment]
👍

**Comment by st3v3nhunt** [comment]
Repo is no longer maintained.
